In [2]:
import numpy as np

In [3]:
#Basic numpy array creation 

In [4]:
arr = np.array([1,2, 3, 4, 5, 6])

In [5]:
print(arr)

[1 2 3 4 5 6]


In [6]:
a = [1, 2, 3.5, "hello"]
a

[1, 2, 3.5, 'hello']

In [7]:
np.array(a) #it will automatically convert all elements to a suitable datatype to keep itself homogenous

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [8]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function

In [10]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [12]:
arr = np.ones((2, 3))
arr #2d array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr = np.linspace(1, 5, 3)
arr

# Return evenly spaced numbers over a specified interval.
# Returns `num` evenly spaced samples, calculated over the
# interval [`start`, `stop`].

array([1., 3., 5.])

In [14]:
print("hello vs code2")

hello vs code2


Random Generation Function

In [17]:
np.random.rand(10)#generate an array with given x elements randomly between 0 and 1 by default
#when values are generated between 0 and 1 -> this is concept of normalization

#in standardization the values are generated between -3 and 3

array([0.6456554 , 0.84088572, 0.96748434, 0.53658163, 0.48219206,
       0.38736565, 0.2547075 , 0.04638854, 0.10123742, 0.43125082])

In [24]:
np.random.randn(10)
#in standardization the values are generated between -3 and 3

array([ 0.65438431, -0.64256464, -1.37007281,  1.32329931,  0.42254331,
       -2.40939338, -0.17948428,  0.97397786, -1.79739901, -0.95133485])

In [25]:
np.random.randint(6) #genrates only one random int from 0 to 6

2

In [26]:
np.random.randint(10, 20, 10) #low, high, how many

array([16, 16, 10, 18, 15, 13, 10, 19, 18, 14], dtype=int32)

Array attributes

In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.shape #this is an attribute, give dimensions of array

(3, 3)

In [30]:
arr.size #gives sixe of array

9

In [31]:
arr.dtype #give data type of array

dtype('int64')

Array Methods

In [32]:
arr.min()

np.int64(1)

In [33]:
arr.max()

np.int64(9)

In [34]:
arr.sum() #gives summ of all elements in the array

np.int64(45)

In [38]:
np.sum(arr, axis = 0) # axis is column, this is used for columnwise sum, axis 1 for rowwise, axis 0 for columnwise

array([12, 15, 18])

In [39]:
arr.mean()

np.float64(5.0)

In [40]:
arr.std()

np.float64(2.581988897471611)

In [41]:
arr.argmax() #index of max element

np.int64(8)

In [43]:
arr.argmin() #index of min element

np.int64(0)

In [45]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [46]:
arr = arr.reshape(6, 5) #reshape dimensions of the array, store this new array in arr itself->resizng

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])