In [2]:
import numpy as np

In [2]:
#Basic numpy array creation 

In [3]:
arr = np.array([1,2, 3, 4, 5, 6])

In [4]:
print(arr)

[1 2 3 4 5 6]


In [5]:
a = [1, 2, 3.5, "hello"]
a

[1, 2, 3.5, 'hello']

In [6]:
np.array(a) #it will automatically convert all elements to a suitable datatype to keep itself homogenous

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [7]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function

In [9]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [11]:
arr = np.ones((2, 3))
arr #2d array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr = np.linspace(1, 5, 3)
arr

# Return evenly spaced numbers over a specified interval.
# Returns `num` evenly spaced samples, calculated over the
# interval [`start`, `stop`].

array([1., 3., 5.])

In [13]:
print("hello vs code")

hello vs code
