In [2]:
import numpy as np

Array Operations

Arithmetic operations

In [4]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6, 7, 8, 9, 10])
a2

array([ 6,  7,  8,  9, 10])

In [7]:
arr2 = a1+a2
#the numbers in array a1 and a2 are added respectively
#only happens when: shape of arrays must be same
arr2

array([ 7,  9, 11, 13, 15])

In [8]:
a1-a2
#array subtraction

array([-5, -5, -5, -5, -5])

In [10]:
a1*a2
#array multiplication

array([ 6, 14, 24, 36, 50])

In [11]:
a1/a2
#array divisions

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1//a2
#floor division

array([0, 0, 0, 0, 0])

In [13]:
a1**a2
#expontial of array elements: element wise

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
array = np.array([1, 2, 3, 4, 5])
array += 10
array #this is called broadcasting when an operation is applied to every element of the array

array([11, 12, 13, 14, 15])

In [21]:
arr2 = np.arange(1,26).reshape(5, 5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
arr2 += 10

In [25]:
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [26]:
arr3 = np.arange(1, 21)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice = arr3[:5]
slice #slice of array is a shallow copy
#a new memory in ram is assigned to it
#unlike list whose slice is a deep copy

array([1, 2, 3, 4, 5])

In [31]:
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [33]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
arr3[4:6]*10
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b = arr3 #this creates a deep copy, as you are copying whole array 

In [39]:
b[0] = 1
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
#to avoid the  deepcopy use .copy()method
c = arr3.copy()
c[0] = 0
arr3 #no changes in c are reflected

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix operations

In [41]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [42]:
A

array([[1, 2],
       [3, 4]])

In [43]:
B

array([[5, 6],
       [7, 8]])

In [45]:
A*B #gave a element to element multiplication

array([[ 5, 12],
       [21, 32]])

In [ ]:
#what we want is the mathematical multiplication of matrix
resultArray = A@B
#or you can use np.dot(A, B)
resultArray #this is the result of how matrix dot multiplication look in mathematics

array([[19, 22],
       [43, 50]])

In [48]:
#transpose of an array
A.T

array([[1, 3],
       [2, 4]])

Advanced Array Manipulation

stacking of arrays

In [61]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
#stacking the arrays requires vectors not matrix

In [62]:
# vertical stack
np.vstack((a, b)) #has only one positional argument
#hence we have to send arrays in a tuple form

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [63]:
np.hstack((a,b)) #horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
np.column_stack((a, b)) #column stack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [65]:
np.row_stack((a, b))

C:\Users\prana\AppData\Local\Temp\ipykernel_14756\2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Splitting array

In [67]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c, 2) #splits the matrix into equal parts
#cuts x axis

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [75]:
a = np.vsplit(c, 4)
#cuts y-axis

In [ ]:
for i in a:
    print(i)
#gives four arrays as split into 4 parts above

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


In [78]:
sample = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sample

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
vertical_lines = np.hsplit(sample, 3)

for line in vertical_lines:
    sum = 0
    print(line)
    for num in line:
        sum += num
    print(int(sum))
    if(sum == 12):
        print("The sum is ", int(sum))
    print('#####')



[[1]
 [4]
 [7]]
12
The sum is  12
#####
[[2]
 [5]
 [8]]
15
#####
[[3]
 [6]
 [9]]
18
#####


C:\Users\prana\AppData\Local\Temp\ipykernel_14756\4145060402.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(int(sum))
C:\Users\prana\AppData\Local\Temp\ipykernel_14756\4145060402.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print("The sum is ", int(sum))


In [80]:
np.vsplit(sample, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]