In [1]:
import numpy as np

**Valid Sudoku**

In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
#Soduku rules
#sudoku has 9 cells, with a 3by3 division
#it has 9 rows and 9 columns
#the sum of whole row or column should be 45, so that all numbers are unique between 1 to 9

In [42]:
#My Solution
isSudokuValid = True
vertical_lines = np.hsplit(s, 9)

for line in vertical_lines:
    sum = 0
    for num in line:
        sum += num
    if (sum!=45):
        isSudokuValid = False

horizontal_lines = np.vsplit(s, 9)

for line in horizontal_lines:
    sum = 0
    for num in line[0]:
        sum += num
    if(sum != 45):
        isSudokuValid = False

for i in range(3):
    for j in range(3):
        block = s[3*i:3*(i+1), 3*j:3*(j+1)]
        if (np.sum(block) != 45):
            isSudokuValid = False

if(isSudokuValid):
    print("The given example of the sudoku is valid")
else:
    print("The given example of the sudoku is not valid")


The given example of the sudoku is valid


In [37]:
#Instructor's solution follow up
validity = True
rowSumArray = np.sum(s, axis = 1) #for row sum
for sum in rowSumArray:
    if(sum != 45):
        validity = False

colSumArray = np.sum(s, axis = 0)
for sum in colSumArray:
    if(sum != 45):
        validity = False


#block (3,3) checking

for i in range(3):
    for j in range(3):
        block = s[3*i:3*(i+1), 3*j:3*(j+1)]
        if (np.sum(block) != 45):
            validity = False


print("The validity of sudoku: ", validity)


The validity of sudoku:  True


**General Questions**

In [74]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [75]:
#Get the shape of the matrix.
# np.shape(data)
data.shape

(5, 3)

In [76]:
#Find average age of students.
print("The average of the data: ",np.average(data[:, 0]))
print("The average of the data: ",np.mean(data[:,0]))

The average of the data:  18.4
The average of the data:  18.4


In [77]:
#Extract Math marks of all students.
#math marks is second column
print(data[:, 1])

[85 92 76 65 90]


In [78]:
#Find the highest Science mark.
highest_marks_in_science = data[:, 2].max()
print(highest_marks_in_science)


95


In [79]:
#Get details of the student who scored more than 90 in Math.
for vec in data:
    if vec[1] >= 90:
        print(f"The student's age is {vec[0]}, he scores {vec[1]} in maths and {vec[2]} in science")


The student's age is 19, he scores 92 in maths and 88 in science
The student's age is 20, he scores 90 in maths and 85 in science


In [80]:
# following instructor's approach for above question
data[data[:, 1] > 90]

array([[19, 92, 88]])

In [81]:
#Increase Math marks of all students by 5.
#use=ing broadcasting
newData = data[:, 1]+ 5
newData

array([90, 97, 81, 70, 95])

In [82]:
#Find how many students are younger than 19.
len(data[data[:, 0] < 19])

3

In [83]:
#Calculate the average marks in each subject (column-wise mean).
# data[:, 1:3].mean(axis = 0)
# data[:, 1:].mean(axis = 0)
#or u can use
np.mean(data[:, 1:], axis = 0)

array([81.6, 83.2])

In [84]:
#Get data of students who scored at least 80 in both subjects.
# data[(data[:, 1] >= 80) and (data[:, 2] >= 80)]
data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]
#here the classical 'and' does not work, we have to use '&'

array([[19, 92, 88],
       [20, 90, 85]])

In [85]:
#Replace all Science marks < 75 with 0.
data[:, 2][data[:, 2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])