In [1]:
import numpy as np 

In [3]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
#indexing is same as list
print(arr[9])

20


In [13]:
#slicing
print(arr[1:5:1]) #start, end+1, steps here four elements are sliced
print(arr[1::2])

[12 13 14 15]
[12 14 16 18 20]


NUMPY INDEXING AND SLICING OF MATRIX

In [14]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
arr[0] #gives the 0th row
# arr[1] #gives the 1th row
# arr[2] #gives the 2th row
# arr[3] #gives the 3th row
# arr[4] #gives the 4th row
# arr[5] #gives the 5th row

array([26, 27, 28, 29, 30])

In [22]:
#getting an element
print(arr[0, 4]) #this is how 2d indexing works in numpy
print(arr[0][3])

5
4


In [27]:
#slicing of matrix
#example slice out 2, 7, 3, 8
#col 1, 2 THERFORE WRITE 1:3
#row 0, 1 THERFORE WRITE 0:2
slice = arr[0:2, 1:3]
slice

array([[2, 3],
       [7, 8]])

In [28]:
#ex slice out 19, 20, 24, 25, 29, 30
slice2 = arr[3:6, 3:5] #similar to arr[3:, 3:] as by default we want to go to end
slice2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [31]:
arr[:, 2] #slicing a column #give a vector

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDEXING

In [33]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
#we want all even numbers from an array
bool_index = arr%2==0
bool_index #creates an array of T or F, for the given condition

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [35]:
arr = arr[bool_index]
arr #only true indiced elements will be reassigned in the array

array([12, 14, 16, 18, 20])